title: Yu Zhou's Home Page
author: Yu Zhou
email: econyz1216@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yu Zhou, Wuhan University, Finance, Master
baseurl: 
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: KelvinZhou

# Build settings
markdown: kramdown

